### ISSUE TITLE
bcc

### ISSUE THREAD

**Issue by sbarex** [sj26/mailcatcher#122]
When send an email with address on bcc the blindend addresses are visibile in the interface in the column To and this make a bit of confusion...
When view the source of the email the bcc addresses i correctly not presents.

**Comment by Splines** [comment]
> When you are sending a BCC e-mail, you must make sure that this address [...] [does] not [...] show up. That said, differ the "recipients" to "bcc recipients" is a feature missing; not implemented. ~ by @taiar [here](https://github.com/sj26/mailcatcher/issues/17#issuecomment-241508692)

I totally agree with @taiar here. Just stumbled upon this since I thought we were erroneously sending mails via _To_ instead of _Cc_. I appreciate if the UI could make this more clear, e.g. by renaming _To_ to _To/Cc/Bcc_ in the table header and linking to #17.

Maybe, you could also separate these fields to multiple columns? For example, would it be possible to classify recipients as _Bcc recipients_ whenever they do _not_ appear in the _To_/_Cc_ mail headers, but still got a mail sent?

**Comment by sj26** [comment]
Again, we can infer, but not be sure.

It might be reasonable to visually indicate when the recipient doesn’t appear in any address list (to, cc) in the email body. It’s tricky, equating delivered addresses with address list entries is more art than science, but likely possible.
