### ISSUE TITLE
Incorrect Unicode JSON encoding

### ISSUE THREAD

**Issue by tsjost** [sj26/mailcatcher#154]
The JSON output of /messages/:id.json is mangling all UTF-8 characters into \ufffd\ufffd.

In the web application message['source'].encoding is set to 'ASCII-8BIT', likely reflecting the Content-Transfer-Encoding, but breaking .to_json

I don't do Ruby so I wouldn't know what a proper solution would be, but I worked around this by doing the following before message.merge(
```
message['source'].force_encoding('UTF-8')
````

Raw email:
```
From: Testing <testing@localhost.local>
To: receiver@localhost.local
Date: Mon, 18 Aug 2014 17:51:26 +0200
Message-ID: <53f220fe58644dfb827100d80a00020f@localhost.local>
Subject: =?UTF-8?B?UsOka3Ntw7ZyZ8OlcyE=?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Hällö tästing räksmörgås!
```

JSON output:
```
{
  "id":1,
  "sender":"",
  "recipients":[""],
  "subject":"R\u00e4ksm\u00f6rg\u00e5s!",
  "source":"From: Testing \nTo: receiver@localhost.local\nDate: Mon, 18 Aug 2014 17:51:26 +0200\nMessage-ID: <53f220fe58644dfb827100d80a00020f@localhost.local>\nSubject: =?UTF-8?B?UsOka3Ntw7ZyZ8OlcyE=?=\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n\nH\ufffd\ufffdll\ufffd\ufffd t\ufffd\ufffdsting r\ufffd\ufffdksm\ufffd\ufffdrg\ufffd\ufffds!\n\n\n\n",
  "size":"348",
  "type":"text/plain",
  "created_at":"2014-08-18T15:51:26+00:00",
  "formats":["source","plain"],
  "attachments":[]
}
```
(Also ```sender``` and ```recipients``` is empty for some reason)

**Comment by sj26** [comment]
SMTP doesn't natively support UTF-8 over the wire. This message, if transmitted raw, doesn't actually conform to the protocol. Some servers support an SMTP UTF-8 extension, but this must be negotiated with EHLO and mailcatcher doesn't support it.

Instead, your mail client should be encoding your message body with  base64 or similar instead of transferring in straight 8-bit. I suspect the body is actually being munged on read then causing transcoding errors on jsonification. For me, this throws an exception at read time. (Encodings in ruby are awful at the best of times.)

If I send your raw email body with catchmail then the mail gem picks up the content and correctly encodes it as base64 and it comes out as expected:

```
{
  "id":3,
  "sender":"\u003ctesting@localhost.local\u003e",
  "recipients":["\u003creceiver@localhost.local\u003e"],
  "subject":"Räksmörgås!",
  "source":"Date: Mon, 18 Aug 2014 17:51:26 +0200\r\nFrom: Testing \u003ctesting@localhost.local\u003e\r\nTo: receiver@localhost.local\r\nMessage-ID: \u003c53f220fe58644dfb827100d80a00020f@localhost.local\u003e\r\nSubject: =?UTF-8?Q?R=C3=A4ksm=C3=B6rg=C3=A5s!?=\r\nMime-Version: 1.0\r\nContent-Type: text/plain;\r\n charset=UTF-8\r\nContent-Transfer-Encoding: base64\r\n\r\nSMOkbGzDtiB0w6RzdGluZyByw6Rrc23DtnJnw6VzIQo=\r\n",
  "size":"368",
  "type":"text/plain",
  "created_at":"2015-01-17T05:44:07.000+00:00",
  "formats":["source","plain"],
  "attachments":[]
}
```
