### ISSUE TITLE
missing header navigation... 

### ISSUE THREAD

**Issue by chrishough** [sj26/mailcatcher#171]
According to your docs, I should see a quit button in the upper right hand corner.. 

![screen shot 2014-11-04 at 11 24 52 pm](https://cloud.githubusercontent.com/assets/744056/4914066/e4310d8a-64bc-11e4-9ba7-c7f1c5c7035d.png)

For the life of me, I can not seem to figure out how to turn that on... 

![screen shot 2014-11-04 at 11 23 51 pm](https://cloud.githubusercontent.com/assets/744056/4914071/f80bda9c-64bc-11e4-826b-bea2b047b950.png)

Thoughts?

**Comment by eric1234** [comment]
I believe this is because you have mailcatcher in your Gemfile. Due to version constraints it is installing and using an old version of mailcatcher.

As the mailcatcher README suggests, don't put that in your Gemfile, just install manually. Just add something to your readme that it needs to be installed or you can expect to keep getting version conflict problems.

**Comment by chrishough** [comment]
Yes, that was the issue, however, I have few more questions regarding this setup in case anyone comes across this same post. 

**Please Note** in order to run mailcatcher using rbenv you have to start it outside your project folder, or you may get this error trying to start it:
```
/Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/rubygems_integration.rb:309:in `block in replace_bin_path': undefined method `name' for nil:NilClass (NoMethodError)
	from .bundle/binstubs/mailcatcher:16:in `<main>'
```

![screen shot 2015-01-02 at 12 21 51 pm](https://cloud.githubusercontent.com/assets/744056/5599404/80a28776-927a-11e4-94ae-03b571566222.png)
