### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by murraybiscuit** [sj26/mailcatcher#255]
After a few hours of the process running in my console, with browser open, my OS complains that it's short on memory and suggests that mailcatcher be shut down.

OS: Win 10
Mailcatcher version: 0.6.2
Browser: Chrome
Shell: git bash

**Comment by sj26** [comment]
*sigh*

Unfortunately this is probably a leak in eventmachine somewhere. I am unable to diagnose it locally. Latest mailcatcher for me runs stably and even recovers resident memory after a little while.

If you'd care to do some delving with https://github.com/tmm1/stackprof and see what's happening that would be wonderful. Otherwise I have no way to reproduce or fix this.

**Comment by murraybiscuit** [comment]
Understood. I'm not a Ruby guy, I'll see what I can do.
