### ISSUE TITLE
retrieve a message by Message-ID key.

### ISSUE THREAD

**Issue by nabedge** [sj26/mailcatcher#287]
Hi. This mailcatcher is so verry looks good to me !
To better , if there is a function that can retrieve a message by Message-ID key.

Application send a mail to mailcatcher smtp like this.

```
Message-ID: <foo.bar.9999@example.com>
Subject: foo

this is body...
```

and my test code  get this mail by http://localhost:1080/message/foo.bar.9999%40example.com as json or plainText.

regards.

**Comment by sj26** [comment]
This is super difficult because your application could send multiple messages with the same Message-ID (although it shouldn't). This feature won't be added to MailCatcher core at the moment, although maybe in the future there will be a better search API.

Maybe use the MailCatcher API to walk the messages and find the one you're after.
