### ISSUE TITLE
Different render mails

### ISSUE THREAD

**Issue by fradee** [sj26/mailcatcher#341]
Hi! Mailcatcher it's amazing software.
Proposition future functionality: **render catched mails as popular email clients - it prevents many front-end's headaches!**

**Comment by sj26** [comment]
I'd love to do this! But I have no idea how.

I tried a while ago to offer integration with a service that did this, but then they wanted lots of money and this is an open source tool. Something like Litmus would be cool. But they're all paid services which require integration keys and things.

The best I could figure out was to offer a _Download_ button and let folks upload to their email testing service of choice.

I'm going to close this for now, because I don't think we can do anything more, but if you think of a way to do this please comment further!
