### ISSUE TITLE
Program freeze

### ISSUE THREAD

**Issue by shivabhusal** [sj26/mailcatcher#350]
> With Ruby 2.4.0
![image](https://user-images.githubusercontent.com/8004593/29459484-7e90f8d8-8443-11e7-9d33-92faa3205710.png)

## Problem:
The web portal won't load properly; program freezes. But works fine with Ruby 2.3.3

**Comment by edwardmp** [comment]
Encountered the same issue here today

**Comment by halilim** [comment]
Do you mean that it doesn't respond to Ctrl+C by "freezes"? If so I'm having that part since for a while with Ruby 2.3.4 too (on both macOS Sierra & High Sierra for what it's worth), having to `kill -9` it.

**Comment by sj26** [comment]
mailcatcher 0.6.5 runs just fine for me on macOS 10.12.6 using Ruby 2.4.1. Support for macOS and 2.4.x are fine.

Could you please elaborate on "The web portal won't load properly" - what exactly does this mean — nothing loads at all? no messages are shown? the connection is interrupted?

What version of macOS are you running? High Sierra has known problems with programs which daemonise, which MailCatcher does. Try running `mailcatcher --foreground` on High Sierra and see if that helps.

It does look like MailCatcher is failing to listen to the ports correctly or daemonise somehow.

**Comment by halilim** [comment]
Oh, please completely forget what I have said. And thanks much @sj26! Trying `mailcatcher --foreground` allowed me to see my problem:

```
$ mailcatcher --foreground
/usr/local/opt/rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/mailcatcher-0.2.4/bin/mailcatcher:42:in `<top (required)>': invalid option: --foreground (OptionParser::InvalidOption)
	from /usr/local/opt/rbenv/versions/2.4.2/bin/mailcatcher:23:in `load'
	from /usr/local/opt/rbenv/versions/2.4.2/bin/mailcatcher:23:in `<main>'
```

Yeah, somehow I was running 0.2.4 all the time. The reason is probably the rbenv mishaps I had some time ago. I'm putting this here rather than deleting the original comment in case somebody else has the same problem.

Talking about versions, I think showing the mailcatcher (and Ruby?) version in the output would be useful.
