### ISSUE TITLE
add websocket heartbeat

### ISSUE THREAD

**Issue by volth** [sj26/mailcatcher#402]
Currently, the intervals between websocket messages is the interval between incoming emails.
So, it could be an hour or few hours.

When there is `nginx` or another reverse proxy in front of mailcatcher, it won't keep an inactive socket open for so long time and will eventually close websocket connection unnoticeable for `mailcatcher`. And `mailcatcher` won't refresh.

So it would be nice if `mailcather` send heatbeat messages every 30-60 seconds (and display "no connection to server" when the last 2-3 heatbeats were not answered)

I am not familiar with Ruby ecosystem, but I believe there must be a ready solution for robust websocket connections

**Comment by sj26** [comment]
Great idea!

For context, when mailcatcher was written, websockets were brand new, so I wrote a websocket implementation which worked well enough. This implementation is deeply integrated with thin, the web application server being used, and these are deeply integrated with EventMachine, which provides the underlying reactor model which allows integrating the HTTP and SMTP servers into the same process and environment.

Adopting an alternative websocket implementation would be quite a lot of work, and a fairly major refactor. Although rewriting mailcatcher using a different core is something I've been wanting to do for agents — eventmachine is severely languishing.

For now, the layer below the websocket should be doing enough to keep the connection alive. Heartbeats within websockets are great when you're traversing the whole Internet and can't rely on tcp to do the right thing, but mailcatcher is designed to run on localhost so shouldn't suffer this problem in the majority case.

I'm going to close this for now because it's not immediately actionable, but any future reimplementation will include some sort of websocket keepalive behaviour. Thank you for your interest!
