### ISSUE TITLE
HTML preview and title cached between clears

### ISSUE THREAD

**Issue by sdsznsk** [sj26/mailcatcher#428]
### This issue was found on **v0.8.0.beta1** version of mailcatcher!

We found and issue with new beta version, where if you use Clear button in top right- it somehow caches the subject and HTML preview of some messages. We use a single instance. Eg. 

Lets say that you have a message with subject "Foo" and some HTML tags that result in "Bar" text in HTML preview. After you clear via top right button, and then send a message with completely different subject and body, its subject will still use "Foo" subject and "Bar" body. If you click on this mail and go to its Source, it will show a proper new source, despite HTML preview still showing "Bar".

It was replicated 100% of the time and went away after downgrade to 0.7.1.

Unfortunately I can't post screenshots due to sensitive informations, but will try to replicate the issue on my private local instance in couple of hours.

**Comment by unikitty37** [comment]
This is happening for me as well with v0.8.0.beta2.

To reproduce from a fresh MailCatcher install:

1. Send an HTML email with body `<p>This is a test.</p><p><em>Look, bold text!</em></p>`
1. View the email in MailCatcher; click the HTML and Plain Text tabs but *not* the Source tab
1. Click `Clear` and confirm
1. Send a different HTML email (in this case, a Devise email address confirmation)
1. View the email in MailCatcher; click all three tabs

## Expected behaviour

The new email is displayed in all three tabs.

## Actual behaviour

The old email is displayed in the HTML and Plain Text tabs, which were viewed in step 2. (In the example images, the Plain Text tab is displaying an even older plain-text-only message…)

The source of the new email is displayed in the Source tab, which was not viewed in step 2.

Browser: Firefox Developer 85.0b5
OS: macOS 10.14.6 (18G6042)

![Screenshot 2021-01-11 at 11 31 34](https://user-images.githubusercontent.com/139183/104178014-9798b500-5401-11eb-9c45-745c522597a0.png)
![Screenshot 2021-01-11 at 11 33 20](https://user-images.githubusercontent.com/139183/104178018-9a93a580-5401-11eb-8947-fb2bb78c8d2d.png)
![Screenshot 2021-01-11 at 11 33 29](https://user-images.githubusercontent.com/139183/104178032-9ebfc300-5401-11eb-8f85-6adbdd98a5da.png)

**Comment by holstvoogd** [comment]
FYI: It is fixed in beta3

**Comment by sj26** [comment]
Thanks for the report, but yes this should be fixed in beta3. Please reopen if not.
