### ISSUE TITLE
Running mailcatcher on a linux virtual machine

### ISSUE THREAD

**Issue by st32lthx** [sj26/mailcatcher#89]
I have installed the Mailcatcher gem (http://mailcatcher.me/) on my VM managed by Vagrant. And in the Vagrantfile I have set up the forwarding port:

```
config.vm.forward_port 1080, 1080
```

I ssh to the guest, run the Mailcatcher on the guest, but when I go to: 127.0.0.1:1080 on my host, I don't see the Mailcather interface. All I get is:

```
No data received.Unable to load the webpage because the server sent no data ...
```

Any ideas?

Thanks in advance!

**Comment by mikedhart** [comment]
Thank you @sj26

**Comment by Moulde** [comment]
Thanks, the command mailcatcher --ip=0.0.0.0 solved my issues. But i think in my issue it was nothing more than the mailcatcher daemon not running - i just didnt know you could start it using that command.

**Comment by sgb-io** [comment]
thanks @sj26 !

**Comment by cristianfrasineanu** [comment]
Indeed the solution with the --http-ip flag did the trick, cheers!

**Comment by facundofarias** [comment]
I just did mailcatcher --ip 192.168.10.10, in which 192.168.10.10 is the VM IP.

**Comment by 64kramsystem** [comment]
> Thanks, the command mailcatcher --ip=0.0.0.0 solved my issues. But i think in my issue it was nothing more than the mailcatcher daemon not running - i just didnt know you could start it using that command.

I've experienced the same issue, and I've found that the problem is that using `--http-ip 0.0.0.0` is necessary to access the web interface from external hosts (otherwise, connections are refused).

@sj26 I suggest to document this somewhere, because it's not obvious, and there's a high risk to spend time looking for the cause somewhere else (firewall(s), typically) before finding the actual solution.
